### ISSUE TITLE
starting the wemo-bridge.jar exits with errors

### ISSUE THREAD

**Issue by supremedk1** [unrelatedlabs/java-wemo-bridge#1]
Hi,

if i start the wemo-bridge.jar it ends with these errors:

14:16:49.348 [main] DEBUG org.eclipse.jetty.util.log - Logging to Logger[org.eclipse.jetty.util.log] via org.eclipse.jetty.util.log.Slf4jLog
14:16:49.359 [main] DEBUG o.e.j.u.component.ContainerLifeCycle - org.eclipse.jetty.server.Server@2d363fb3 added {qtp292938459{STOPPED,8<=0<=200,i=0,q=0},AUTO}
14:16:49.366 [main] DEBUG o.e.j.u.component.ContainerLifeCycle - HttpConnectionFactory@299a06ac{HTTP/1.1} added {HttpConfiguration@383534aa{32768,8192/8192,https://:0,[]},POJO}
14:16:49.367 [main] DEBUG o.e.j.u.component.ContainerLifeCycle - ServerConnector@5577140b{null}{0.0.0.0:0} added {org.eclipse.jetty.server.Server@2d363fb3,UNMANAGED}
14:16:49.367 [main] DEBUG o.e.j.u.component.ContainerLifeCycle - ServerConnector@5577140b{null}{0.0.0.0:0} added {qtp292938459{STOPPED,8<=0<=200,i=0,q=0},AUTO}
14:16:49.367 [main] DEBUG o.e.j.u.component.ContainerLifeCycle - ServerConnector@5577140b{null}{0.0.0.0:0} added {org.eclipse.jetty.util.thread.ScheduledExecutorScheduler@7382f612,AUTO}
14:16:49.368 [main] DEBUG o.e.j.u.component.ContainerLifeCycle - ServerConnector@5577140b{null}{0.0.0.0:0} added {org.eclipse.jetty.io.ArrayByteBufferPool@1c6b6478,POJO}
14:16:49.368 [main] DEBUG o.e.j.u.component.ContainerLifeCycle - ServerConnector@5577140b{null}{0.0.0.0:0} added {HttpConnectionFactory@299a06ac{HTTP/1.1},AUTO}
14:16:49.369 [main] DEBUG o.e.j.u.component.ContainerLifeCycle - ServerConnector@5577140b{HTTP/1.1}{0.0.0.0:0} added {org.eclipse.jetty.server.ServerConnector$ServerConnectorManager@43556938,MANAGED}
14:16:49.369 [main] DEBUG o.e.j.u.component.ContainerLifeCycle - org.eclipse.jetty.server.Server@2d363fb3 added {ServerConnector@5577140b{HTTP/1.1}{0.0.0.0:9700},AUTO}
Exception in thread "main" java.lang.NullPointerException
        at com.unrelatedlabs.wemo.WemoBridge.main(WemoBridge.java:60)

There is no more info or anything else, I can't debug anything more.

Greetings

**Comment by unrelatedlabs** [comment]
Hi,

What platform? Which java version?

Br,
Peter

**Comment by damiene77** [comment]
Hello,

Is this still being supported.  Getting same error as above.
Debian 4.4.13-v7+ on RPI3
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) Client VM (build 25.65-b01, mixed mode)

Thanks

**Comment by unrelatedlabs** [comment]
yes, still works.

Use this if you have problems:

https://github.com/unrelatedlabs/java-wemo-bridge/blob/master/target/wemo-bridge-0.0.1-SNAPSHOT-jar-with-dependencies.jar

Especially on Linux.

**Comment by apkuhar** [comment]
I've updated the README.md
